# Generated by Django 5.0.2 on 2024-02-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_rename_inventory_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price_per_unit',
            new_name='buying_price',
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
    ]
