# Generated by Django 5.0.2 on 2024-03-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_recipe_alter_stock_food_alter_stock_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Name of Recipe'},
        ),
        migrations.AlterField(
            model_name='stock',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
