# Generated by Django 5.0.2 on 2024-03-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_alter_recipe_options_alter_stock_price_per_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredient',
            field=models.ManyToManyField(through='Inventory.RecipeIngredient', to='Inventory.stock'),
        ),
    ]
