# Generated by Django 5.0.2 on 2024-03-07 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0007_recipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='stock',
            name='food',
            field=models.CharField(max_length=100, verbose_name=' Food Name'),
        ),
        migrations.CreateModel(
            name='RecipePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.recipe')),
            ],
        ),
    ]
