# Generated by Django 5.0.2 on 2024-03-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_remove_recipe_ingredient_alter_stock_food_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeprice',
            old_name='price',
            new_name='production_price',
        ),
        migrations.AddField(
            model_name='recipeprice',
            name='gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recipeprice',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
