# Generated by Django 5.0.2 on 2024-03-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_rename_price_recipeprice_production_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='buying_price',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=10),
        ),
    ]
