# Generated by Django 5.0.2 on 2024-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0011_alter_recipeprice_production_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sales of the day'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
