# Generated by Django 5.0.2 on 2024-03-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_alter_sales_options_alter_sales_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='total_gain',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_production_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sales',
            name='total_sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
